### ISSUE TITLE
Cannot create translation because of stupid typo

### ISSUE THREAD

**Issue by liberium** [nganhtuan63/gxc-cms#22]
Please add '>' to '<h1' in GXC-CMS / core / cms1.0 / modules / translate / views / edit / form.php

**Comment by nganhtuan63** [comment]
I only found </h1 on line 2. Its from Translate module. I will remove that tag </h1>. Ok ?

**Comment by liberium** [comment]
NO!!!!
please note that < /h1 > has no ">".

**Comment by ametad** [comment]
I cannot find the H1 tag in that view. Perhaps it is already done..? The class is correct I believe.

**Comment by nganhtuan63** [comment]
Ya, it is fixed!
